// <auto-generated />
using System;
using CompteDepot.Simple.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace CompteDepot.Simple.Migrations
{
    [DbContext(typeof(BanqueContext))]
    partial class BanqueContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.9")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("CompteDepot.Simple.Models.CompteDepot", b =>
                {
                    b.Property<string>("NumeroCompte")
                        .HasColumnType("text");

                    b.Property<DateTime>("DateCreation")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("DateEcheance")
                        .HasColumnType("timestamp with time zone");

                    b.Property<decimal>("MontantRetireAnnee")
                        .HasColumnType("numeric");

                    b.Property<decimal>("MontantRetireMois")
                        .HasColumnType("numeric");

                    b.Property<string>("Proprietaire")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<decimal>("Solde")
                        .HasColumnType("numeric");

                    b.Property<decimal>("TauxInteret")
                        .HasColumnType("numeric");

                    b.HasKey("NumeroCompte");

                    b.ToTable("ComptesDepot");

                    b.HasData(
                        new
                        {
                            NumeroCompte = "DEP001",
                            DateCreation = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            DateEcheance = new DateTime(2024, 7, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            MontantRetireAnnee = 0m,
                            MontantRetireMois = 0m,
                            Proprietaire = "Jean Dupont",
                            Solde = 5000m,
                            TauxInteret = 2.5m
                        },
                        new
                        {
                            NumeroCompte = "DEP002",
                            DateCreation = new DateTime(2024, 4, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            DateEcheance = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            MontantRetireAnnee = 0m,
                            MontantRetireMois = 0m,
                            Proprietaire = "Marie Martin",
                            Solde = 10000m,
                            TauxInteret = 3.0m
                        });
                });

            modelBuilder.Entity("CompteDepot.Simple.Models.OperationDepot", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("DateOperation")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<decimal>("Montant")
                        .HasColumnType("numeric");

                    b.Property<string>("NumeroCompte")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Operations");
                });
#pragma warning restore 612, 618
        }
    }
}
